name: android

on:
  workflow_dispatch:
  push:
    paths:
      - 'lib/**.[ch]'
      - 'lib/**.cpp'
      - 'src/**.[ch]'
      - 'src/**.cpp'
      - 'irr/**.[ch]'
      - 'irr/**.cpp'
      - '**/CMakeLists.txt'
      - 'cmake/Modules/**'
      - 'po/**.po'
      - 'android/**'
      - '.github/workflows/android.yml'
  pull_request:
    paths:
      - 'lib/**.[ch]'
      - 'lib/**.cpp'
      - 'src/**.[ch]'
      - 'src/**.cpp'
      - 'irr/**.[ch]'
      - 'irr/**.cpp'
      - '**/CMakeLists.txt'
      - 'cmake/Modules/**'
      - 'po/**.po'
      - 'android/**'
      - '.github/workflows/android.yml'

env:
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
  KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends gettext openjdk-17-jdk

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build AAB with Gradle (unsigned)
      run: cd android; ./gradlew bundlerelease

    - name: Build APKs with Gradle (unsigned)
      run: cd android; ./gradlew assemblerelease

    - name: Import Keystore
      run: |
        mkdir -p ~/.android
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > ~/.android/my-release-key.jks

    # APK İmzalama Adımları
    - name: Sign armeabi-v7a APK
      run: |
        jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 \
          -keystore ~/.android/my-release-key.jks \
          -storepass $KEYSTORE_PASSWORD \
          -keypass $KEY_PASSWORD \
          android/app/build/outputs/apk/release/app-armeabi-v7a-release-unsigned.apk $KEY_ALIAS

    - name: Sign arm64-v8a APK
      run: |
        jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 \
          -keystore ~/.android/my-release-key.jks \
          -storepass $KEYSTORE_PASSWORD \
          -keypass $KEY_PASSWORD \
          android/app/build/outputs/apk/release/app-arm64-v8a-release-unsigned.apk $KEY_ALIAS

    - name: Sign x86 APK
      run: |
        jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 \
          -keystore ~/.android/my-release-key.jks \
          -storepass $KEYSTORE_PASSWORD \
          -keypass $KEY_PASSWORD \
          android/app/build/outputs/apk/release/app-x86-release-unsigned.apk $KEY_ALIAS

    - name: Sign x86_64 APK
      run: |
        jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 \
          -keystore ~/.android/my-release-key.jks \
          -storepass $KEYSTORE_PASSWORD \
          -keypass $KEY_PASSWORD \
          android/app/build/outputs/apk/release/app-x86_64-release-unsigned.apk $KEY_ALIAS

    # İmzalama Doğrulama
    - name: Verify armeabi-v7a APK Signature
      run: jarsigner -verify android/app/build/outputs/apk/release/app-armeabi-v7a-release-unsigned.apk

    - name: Verify arm64-v8a APK Signature
      run: jarsigner -verify android/app/build/outputs/apk/release/app-arm64-v8a-release-unsigned.apk

    - name: Verify x86 APK Signature
      run: jarsigner -verify android/app/build/outputs/apk/release/app-x86-release-unsigned.apk

    - name: Verify x86_64 APK Signature
      run: jarsigner -verify android/app/build/outputs/apk/release/app-x86_64-release-unsigned.apk

    # Artifact’leri yükle
    - name: Upload AAB artifact (unsigned)
      uses: actions/upload-artifact@v4
      with:
        name: Luanti-release.aab
        path: android/app/build/outputs/bundle/release/app-release.aab

    - name: Upload Signed armeabi-v7a APK
      uses: actions/upload-artifact@v4
      with:
        name: Luanti-armeabi-v7a-signed.apk
        path: android/app/build/outputs/apk/release/app-armeabi-v7a-release-unsigned.apk

    - name: Upload Signed arm64-v8a APK
      uses: actions/upload-artifact@v4
      with:
        name: Luanti-arm64-v8a-signed.apk
        path: android/app/build/outputs/apk/release/app-arm64-v8a-release-unsigned.apk

    - name: Upload Signed x86 APK
      uses: actions/upload-artifact@v4
      with:
        name: Luanti-x86-signed.apk
        path: android/app/build/outputs/apk/release/app-x86-release-unsigned.apk

    - name: Upload Signed x86_64 APK
      uses: actions/upload-artifact@v4
      with:
        name: Luanti-x86_64-signed.apk
        path: android/app/build/outputs/apk/release/app-x86_64-release-unsigned.apk
